version: '3'
services:

  front-react:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - database


  database:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rssParser
    ports:
      - "5432:5432"

